---
- name: install wget
  apt: name=wget state=present

- name: download Hadoop
  command: bash -c "cd /root && wget http://apache-mirror.rbc.ru/pub/apache/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz" creates=/root/hadoop-{{ hadoop_version }}.tar.gz

- name: unpack Hadoop
  command: bash -c "cd /opt && tar xzf /root/hadoop-{{ hadoop_version }}.tar.gz" creates=/opt/hadoop-{{ hadoop_version }}

- name: create {{ hadoop_distr_prefix }}
  shell: cp -r /opt/hadoop-{{ hadoop_version }} {{ hadoop_distr_prefix }} creates={{ hadoop_distr_prefix }}

- name: add Hadoop user
  user: name={{ hadoop_user }} shell={{ hadoop_user_shell }} state=present

- name: make {{ hadoop_var_prefix }}
  file: path={{ hadoop_var_prefix }} state=directory owner={{ hadoop_user }} group={{ hadoop_user }} mode=0700

- name: put exclusion list
  template: src=hadoop/exclusion-list dest={{ hadoop_var_prefix }}/exclusion-list
  notify: refresh nodes

- name: make {{ hadoop_distr_prefix }}/conf
  file: path={{ hadoop_distr_prefix }}/conf state=directory owner=root group=root mode=0755

- name: put {{ hadoop_distr_prefix }}/conf/core-site.xml
  template: src=hadoop/core-site.xml dest={{ hadoop_distr_prefix }}/conf/core-site.xml owner=root group=root mode=0644

- name: put {{ hadoop_distr_prefix }}/conf/hdfs-site.xml
  template: src=hadoop/hdfs-site.xml dest={{ hadoop_distr_prefix }}/conf/hdfs-site.xml owner=root group=root mode=0644

- name: put {{ hadoop_distr_prefix }}/conf/hadoop-env.sh
  template: src=hadoop/hadoop-env.sh dest={{ hadoop_distr_prefix }}/conf/hadoop-env.sh owner=root group=root mode=0644

- name: put {{ hadoop_distr_prefix }}/conf/yarn-env.sh
  template: src=hadoop/yarn-env.sh dest={{ hadoop_distr_prefix }}/conf/yarn-env.sh owner=root group=root mode=0644
  when: (disable_yarn|default(False) == False)

- name: put {{ hadoop_distr_prefix }}/conf/yarn-site.xml
  template: src=hadoop/yarn-site.xml dest={{ hadoop_distr_prefix }}/conf/yarn-site.xml owner=root group=root mode=0644
  when: (disable_yarn|default(False) == False)

- name: put {{ hadoop_distr_prefix }}/conf/mapred-site.xml
  template: src=hadoop/mapred-site.xml dest={{ hadoop_distr_prefix }}/conf/mapred-site.xml owner=root group=root mode=0644
  when: (disable_yarn|default(False) == False)

- name: create {{ hadoop_distr_prefix }}/lib/native/Linux-amd64-64
  file: state=directory path={{ hadoop_distr_prefix }}/lib/native/Linux-amd64-64

- name: make a link to libhadoop.so
  file: state=link src={{ hadoop_distr_prefix }}/lib/native/libhadoop.so dest={{ hadoop_distr_prefix }}/lib/native/Linux-amd64-64/libhadoop.so

- name: make a link to libhdfs.so
  file: state=link src={{ hadoop_distr_prefix }}/lib/native/libhdfs.so dest={{ hadoop_distr_prefix }}/lib/native/Linux-amd64-64/libhdfs.so
